name: create-index

on:
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: update
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./build.sh
